### PR TITLE
replaces child_process by cross-spawn

### PR DESCRIPTION
**Pull request by 0815fox**
Possible fix for issue #5 

Needs test on windows.

### CODE REVIEW

**Comment by MorgKrig** [comment]
Successfully tested on windows

**Review by MorgKrig — APPROVED** [review]
Successfully tested on windows

**Comment by 0815fox** [comment]
Added --all option to npm ls

**Comment by MorgKrig** [comment]
Sample trees are now correct redrawn with deep dependencies. So we are ready for a merge.

**Pull request merged**
